### PR TITLE
Make ldconfig configurable

### PR DESCRIPTION
**Pull request by ffontaine**
In a cross-compilation set up, running /sbin/ldconfig is useless, so
we make the path to ldconfig configurable through the environment/make
command line. This allows to pass LDCONFIG=/bin/true when doing
cross-compilation.

[Gustavo: update patch for olsr 0.6.4]
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[Retrieved from:
https://git.buildroot.net/buildroot/tree/package/olsr/0001-configurable-ldconfig.patch]

### CODE REVIEW

**Comment by fhuberts** [comment]
This patch is incomplete:
```
$ grep -nri ldconfig
src/cfgparser/Makefile:107:		/sbin/ldconfig -n $(LIBDIR)
make/Makefile.android:134:		/sbin/ldconfig -n $(LIBDIR)
make/Makefile.android:136:		/sbin/ldconfig -n $(LIBDIR)
make/Makefile.obsd:67:		/sbin/ldconfig
make/Makefile.obsd:69:		/sbin/ldconfig
make/Makefile.linux:78:		/sbin/ldconfig -n $(LIBDIR)
make/Makefile.linux:80:		/sbin/ldconfig -n $(LIBDIR)
make/Makefile.fbsd:81:		/sbin/ldconfig
make/Makefile.fbsd:83:		/sbin/ldconfig
make/Makefile.nbsd:60:		/sbin/ldconfig
make/Makefile.nbsd:62:		/sbin/ldconfig
lib/secure/README_SECURE:34:  This will run ldconfig to update the dynamic linker.
lib/pud/wireformat/Makefile:144:	/sbin/ldconfig -n "$(LIBDIR)"
lib/pud/wireformat/Makefile:154:	/sbin/ldconfig -n "$(LIBDIR)"
lib/pud/nmealib/Makefile:93:	$(MAKECMDPREFIX)/sbin/ldconfig -n "$(LIBDIR)"
lib/pud/nmealib/Makefile:102:	$(MAKECMDPREFIX)/sbin/ldconfig -n "$(LIBDIR)"
lib/pud/wireformat-java/Makefile:359:	/sbin/ldconfig -n "$(LIBDIR)"
lib/pud/wireformat-java/Makefile:369:	/sbin/ldconfig -n "$(LIBDIR)"
```

**Comment by ffontaine** [comment]
I updated the PR, I hope everything is ok as I'm not able to test it under all platforms

**Comment by fhuberts** [comment]
did you build?
I think the LDCONFIG is not carried over to sub-make files in your patch

**Comment by ffontaine** [comment]
I'm only able to build under Linux and it builds fine. Sub-makefiles (such as lib/pud/nmealib/Makefile) includes $(TOPDIR)/Makefile.in which defines LDCONFIG to /sbin/ldconfig by default.

**Pull request merged**
