### PR TITLE
Add debian package support to OLSRd repository

### PR DESCRIPTION
**Pull request by mathiashro**
Since Debian removed olsrd from the official package repository and we do not have any active maintainers I prepared all needed filed and updated them as far as I could. Tested on our local server farm (Opennnet Initiative).

There is currently one outstanding item: The resulting olsrd binary is looking for plugins at /usr/lib instead of /usr/lib/olsrd. If someone is able to improve my PR - highly welcome. Also any comment at the whole process.

I'd like to merge it soon, since we are working on a docker-based build process as well and I'd like to finalize that as well.

### CODE REVIEW

**Comment by vchrizz** [comment]
Yes! Please!
So I don't have to clone this repo and update it myself anymore for building debian packages.

To fix /usr/lib/olsrd issue for Debian this should be enough:
```
Makefile.inc
-LIBDIR   ?= $(USRDIR)/lib
+LIBDIR   ?= $(USRDIR)/lib/olsrd
```

**Comment by mathiashro** [comment]
Hello @vchrizz, 

if I remember correctly I found the same patch for the Makefile at older Debian repos but it was not helping here. Do you may have some time for review and testing?

**Comment by vchrizz** [comment]
For what its worth you can have a look at this page where I have set up a Debian/Ubuntu repo for OLSRd packages:
https://repos.freiesnetz.at/
There I also tried to describe in detail how I have set this up and how I build those packages.

(btw. I messaged the Debian maintainer of the OLSRd package a while ago and he told me, if anyone is willing to create Debian packages according to the Debian Package guidelines, he would help with upload/push the packages to the Debian repos)

**Comment by leoss** [comment]
To simplify the review of this PR I created a new PR with a reduced set of commits and without merges, see https://github.com/OLSR/olsrd/pull/133 . When the PR#133 is merged then this PR here can be closed.

**Comment by mathiashro** [comment]
This PR has been superseeded by PR #133

**Pull request closed without merging**
