### PR TITLE
added 320-silent.patch by Markus Kittenberger

### PR DESCRIPTION
**Pull request by vchrizz**
if enabled, reduces amount of tc messages.
olsrd.conf with mode=silent - meant to be used for OpenVPN tunnels.
created by Markus Kittenberger.

### CODE REVIEW

**Comment by fhuberts** [comment]
why is the patch files in this PR?

**Comment by vchrizz** [comment]
sorry, i'm still not fully accustomed using git. wanted to add the patch and did something wrong here.
guess i need to do the whole process again? delete my (already patched) fork, fork again to apply patch then create new pull request without the file?

**Comment by fhuberts** [comment]
just create a new branch or reset the branch to where you want it and push -f

**Comment by vchrizz** [comment]
see https://github.com/OLSR/olsrd/pull/51
hope i got it right this time :)

**Pull request closed without merging**
