### PR TITLE
build: patch for gpsd 3.25

### LINKED ISSUE #118: supporting gpsd 3.25
The `fixsource_t` definition got changed in the [gpsd 3.25 release](https://github.com/ntpsec/gpsd/commit/fde36494daa6eaaba7c366f13a74a331f2054648)

```diff
-/* describe a data source */
-struct fixsource_t {
-    char spec[PATH_MAX]; /* working space, will be modified */
-    char *server; /* pointer into spec field */
-    char *port; /* pointer into spec field */
-    char *device; /* pointer into spec field */
-};
+ // describe a gpsd source
+ struct fixsource_t
+ {
+     char spec[512];               // original string
+     const char *server;           // server name, maybe IP
+     const char *server_ip;        // server IP as string, maybe IPv4 or IPv6
+     const char *port;
+     const char *device;
+ };
```

also the file got moved from gpsdclient.h into gps.h, https://github.com/ntpsec/gpsd/commit/35fe48835da07cb1045e404aef0a582c04fd8da1

### PR DESCRIPTION
**Pull request by chenrui333**
closes #118

relates to https://github.com/Homebrew/homebrew-core/pull/120328

cc @mathiashro

### CODE REVIEW

**Comment by mathiashro** [comment]
@chenrui333, may we have still an compile error? As of the buildtest following environment / libs are been installed:

```
Get:1 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libgps28 amd64 3.[22](https://github.com/OLSR/olsrd/pull/119/checks#step:3:23)-4ubuntu2 [58.3 kB]
Get:2 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libgps-dev amd64 3.22-4ubuntu2 [113 kB]
```

**Comment by chenrui333** [comment]
> @chenrui333, thank you - may we have still an compile error? As of the buildtest following environment / libs are been installed:
> 
> ```
> Get:1 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libgps28 amd64 3.[22](https://github.com/OLSR/olsrd/pull/119/checks#step:3:23)-4ubuntu2 [58.3 kB]
> Get:2 http://azure.archive.ubuntu.com/ubuntu jammy/main amd64 libgps-dev amd64 3.22-4ubuntu2 [113 kB]
> ```

are you referring to the CI failure?

**Comment by mathiashro** [comment]
@chenrui333 correct, the CI pipeline build test is failing. Did not yet had time for my own compile check.

**Comment by mathiashro** [comment]
Build successful via Darwin 22 / Ventura and Debian 11.

e.g.
```
apt install flex bison libc6-dev libgps-dev 
git clone https://github.com/chenrui333/olsrd.git
make build_all
```

**Comment by chenrui333** [comment]
I might check on this today. Sorry about the delay. (we did use the patch to ship gpsd 3.25 though)

**Comment by yann-morin-1998** [comment]
The build failure in the CI is due to the image used to do the build: ubuntu-latest (presumable either one of 22.10 or 22.04LTS) still only ship gpsd 3.22, so it is going to miss that struct defintion in its exported headers.

If we want to have olsrd support gpsd 3.24 or older as well as 3.25 or later, then we must detect at build time whether `struct fixsource_t` is present in gpsd headers or not, and if not define the fallback as it was done before.

olsrd has no configure (or similar), so we can't easily detect features before building; we'll have to resort o testing stuff in the C preprocessor instead. `gps.h` does not define the gpsd version (only its API), so we shouldn't rely on a version comparison to decide whether to do fallback; however, `struct fixsource_t` was moved for API version 14, so maybe that would be good enough: API 14 onward have it, so we do not define it, otherwise we do define it?

**Comment by yann-morin-1998** [comment]
I'm testing a patch: https://github.com/yann-morin-1998/olsrd/tree/yem/issue-118-gpsd-3.25

**Pull request merged**
