### PR TITLE
pud: adapt gpsdclient.c to new gpsd 3.21

### PR DESCRIPTION
**Pull request by PolynomialDivision**
As mentioned:
"Move gps_data_t->status to gps_fix_t.status for better fix merging"
https://gitlab.com/gpsd/gpsd/-/commit/29991d6ffeb41ecfc8297db68bb68be0128c8514

### CODE REVIEW

**Comment by PolynomialDivision** [comment]
I think I will wait with this PR until all major distros update to a version >= 3.21

**Comment by SvenRoederer** [comment]
what about conditional compiling based on GPSD_API_MAJOR_VERSION (https://gitlab.com/gpsd/gpsd/-/commit/29991d6ffeb41ecfc8297db68bb68be0128c8514#fbec23e759c01a5d296e7d1e3a17e9b131df6ae4_84_83)? This will make the code work for both APIs, esp. as it's only a single that is affected.

**Comment by PolynomialDivision** [comment]
Thanks! Good idea. I will change that.

**Comment by PolynomialDivision** [comment]
@SvenRoederer Like that?

**Comment by SvenRoederer** [comment]
something alike or the other way around ...

**Pull request merged**
